apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    tier: backend
spec:
  nodeName: kube-w1
  terminationGracePeriodSeconds: 0
  containers:
  - name: abc
    image: flavian07/abc:v3-1
    ports:
    - containerPort: 8080

    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5